# Generated by Django 2.1 on 2019-03-14 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Row', models.IntegerField()),
                ('Column', models.IntegerField()),
                ('Select_Dimension', models.TextField(default='Row')),
                ('Data', models.CharField(default=None, max_length=1000)),
                ('auth', models.ForeignKey(default=None, on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
